development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql 
  url: postgres://kgxbabrvsikenl:8pwwiL40Tz-y3vDlkL3uJzDTZs@ec2-23-21-193-140.compute-1.amazonaws.com:5432/d8f5cdb4fpsbgp

